global_costmap:
  global_frame: map
  robot_base_frame: base_link
  allow_unknown: false 
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  inflation_radius: 0.7
  cost_scaling_factor: 4
  static_map: true
  rolling_window: false
