joint_limits:
  right_wheel:
    has_position_limits: false
    min_position: 0
    max_position: 0
    has_velocity_limits: true
    max_velocity: 7.4 #2.62 4.62
    min_velocity: -3.62 #-2.62
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0
    min_effort: 0

  left_wheel:
    has_position_limits: false
    min_position: 0
    max_position: 0
    has_velocity_limits: true
    max_velocity: 7.4
    min_velocity: -3.62
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0
    min_effort: 0