local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5 

  static_map: false  
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
  inflation_radius: 0.7
  cost_scaling_factor: 0.75
# plugins:
#   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
#   - {name: static_layer, type: "costmap_2d::StaticLayer"}

# inflater_layer:
#   inflation_radius: 0.35
#   cost_scaling_factor: 0.5


# obstacle_layer:
#   observation_sources: laser_scan_sensor
#   laser_scan_sensor: {sensor_frame: laser_frame, 
# data_type: LaserScan, 
# topic: scan, marking: true, 
# clearing: true, 
# max_obstacle_height: 3, 
# min_obstacle_height: -3, 
# inf_is_valid: true, 
# obstacle_range: 2.5, 
# combination_method: 0,
# raytrace_range: 3}