base_global_planner: SBPLLatticePlanner
SBPLLatticePlanner:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 100.0
  initial_epsilon: 10.0
  forward_search: false
  allow_unknown: false 
  nominalvel_mpersecs: 0.8
  timetoturn45degsinplace_secs: 1.31 # = 0.6 rad/s
  # backward_search: true 
  